### PR TITLE
Update past-participle.js

### PR DESCRIPTION
**Pull request by leonardocrociani**
Added 29 entries

### CODE REVIEW

**Comment by spencermountain** [comment]
hey Leonardo - thanks for this, is this just a formatter change? I can merge this, but I can't see which 29 have been added.
Let me know if I can help. I'm not sure if the formatter settings have been set properly.
Happy to merge this, and your other one - i'm sure there are a lot of good verbs missing.
cheers!

**Comment by leonardocrociani** [comment]
Hi spencer, performing a diff you can check that there are some additional lines : ) 
image
I can provide the specific verbs, if needed.

Have a nice day! :smile:

**Comment by spencermountain** [comment]
Hey Leonardo, apologies for the delay. Will merge this and fix the github script, and release the changes in the next couple days. 
Thanks for your help.

**Comment by leonardocrociani** [comment]
Don't worry Spencer! 
BTW I'm using your package dumpster-dive to download Wikipedia IT.
You are great! :exploding_head:

**Comment by spencermountain** [comment]
hey thanks Leonardo - released your changes as `0.2.2`
there's a bunch of tests failing, mostly verb conjugation issues, and I'd love to crank through them. It may be something wrong with the model compression. Sometimes the long verb suffixes make my eyes spin - would love some help.
have a nice weekend!
cheers

**Pull request merged**
